#!/usr/bin/env python3
"""Write HELP.md and FAQ.md from the manual the app itself reads.

    Scripts/generate-help-docs.py            rewrite both files
    Scripts/generate-help-docs.py --check    exit non-zero if they are stale

WHY GENERATE RATHER THAN WRITE THEM

Seedbed's help is a Swift value, `Manual.sections` in `macos/Sources/Seedbed/
Manual.swift`, and the app is the only surface that renders it. That is a
problem for anyone who has the repository and not a Mac: the tap is a clone,
the public snapshot ships no binary, and until now the only way to read the
help was to build the app.

The obvious fix, a hand-written HELP.md beside the Swift, is the one this
project already refused once, and for a good reason: two copies of the same
prose drift, and the copy nobody renders drifts first. So this takes the
approach the project already uses for the DMG's "Before you start.txt" and the
cask caveats, which are generated from one source for exactly this reason.
One source, two outputs, and a test that fails when they diverge.

WHY IT PARSES SWIFT WITH A REGEX INSTEAD OF ASKING SWIFT

Running the app to dump its own manual would be more robust and is what
`SEEDBED_DUMP_MENU` does for the menu. It is also unavailable where it matters:
`tests/` is Python, runs in the public snapshot with no Swift toolchain, and is
the build gate for `publish-repo.sh`. `tests/test_help_content_freshness.py`
already reads `Manual.swift` as text for the same reason, so this is the
established shape here rather than a new one.

The parser is therefore deliberately narrow. It understands the two forms the
manual actually uses and raises on anything else rather than skipping it,
because a generator that silently drops a topic produces a document that looks
complete and is not.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANUAL = ROOT / "macos" / "Sources" / "Seedbed" / "Manual.swift"

BANNER = (
    "<!-- Generated from macos/Sources/Seedbed/Manual.swift by\n"
    "     Scripts/generate-help-docs.py. Do not edit this file: edit the manual\n"
    "     and regenerate, or tests/test_help_docs_generated.py will fail. -->"
)


class ParseError(RuntimeError):
    """The manual grew a shape this parser does not understand.

    Raised rather than skipped. A topic silently dropped here becomes a gap in
    a published document that still looks finished.
    """


# --------------------------------------------------------------- Swift literals

def _read_string(text: str, i: int) -> tuple[str, int]:
    """Read one Swift string literal starting at `text[i]`. Returns (value, end)."""
    if text.startswith('"""', i):
        end = text.index('"""', i + 3)
        raw = text[i + 3:end]
        lines = raw.split("\n")
        if lines and not lines[0].strip():
            lines = lines[1:]
        if lines and not lines[-1].strip():
            lines = lines[:-1]
        indents = [len(ln) - len(ln.lstrip()) for ln in lines if ln.strip()]
        pad = min(indents) if indents else 0
        lines = [ln[pad:] if len(ln) >= pad else ln.lstrip() for ln in lines]

        # A trailing backslash is Swift's line continuation: it joins to the next
        # line with a space and no newline. Losing this reflows every paragraph
        # in the manual into one line per source line.
        out: list[str] = []
        for ln in lines:
            if out and out[-1].endswith("\\"):
                out[-1] = out[-1][:-1].rstrip() + " " + ln.lstrip()
            else:
                out.append(ln)
        if out and out[-1].endswith("\\"):
            out[-1] = out[-1][:-1].rstrip()
        return "\n".join(out).strip(), end + 3

    if text[i] != '"':
        raise ParseError(f"expected a string literal at offset {i}: {text[i:i + 40]!r}")
    j, buf = i + 1, []
    while j < len(text):
        c = text[j]
        if c == "\\":
            nxt = text[j + 1]
            buf.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\"}.get(nxt, nxt))
            j += 2
            continue
        if c == '"':
            return "".join(buf), j + 1
        buf.append(c)
        j += 1
    raise ParseError(f"unterminated string literal at offset {i}")


def _split_items(block: str) -> list[str]:
    """Split an array literal body on its top-level commas."""
    items, depth, start, i = [], 0, 0, 0
    while i < len(block):
        c = block[i]
        if c == '"':
            _, i = _read_string(block, i)
            continue
        if c in "([{":
            depth += 1
        elif c in ")]}":
            depth -= 1
        elif c == "," and depth == 0:
            items.append(block[start:i])
            start = i + 1
        i += 1
    items.append(block[start:])
    return [s.strip() for s in items if s.strip()]


def _balanced(text: str, open_at: int, opener: str, closer: str) -> str:
    """Return the body between `opener` at `open_at` and its matching `closer`."""
    depth, i = 0, open_at
    while i < len(text):
        c = text[i]
        if c == '"':
            _, i = _read_string(text, i)
            continue
        if c == opener:
            depth += 1
        elif c == closer:
            depth -= 1
            if depth == 0:
                return text[open_at + 1:i]
        i += 1
    raise ParseError(f"unbalanced {opener!r} from offset {open_at}")


# ------------------------------------------------------------------- the manual

def _array_body(src: str, name: str) -> str:
    m = re.search(rf"static let {re.escape(name)}: \[ManualTopic\] = \[", src)
    if not m:
        raise ParseError(f"no topic array named {name!r}")
    return _balanced(src, m.end() - 1, "[", "]")


def _parse_topic(item: str) -> dict:
    if item.startswith("key("):
        args = _split_items(_balanced(item, item.index("("), "(", ")"))
        if len(args) != 2:
            raise ParseError(f"key() takes 2 arguments, got {len(args)}: {item[:60]!r}")
        cap, _ = _read_string(args[0], 0)
        meaning, _ = _read_string(args[1], 0)
        return {"term": cap, "detail": meaning, "example": None, "key": cap}

    if not item.startswith("ManualTopic("):
        raise ParseError(f"unrecognised topic form: {item[:60]!r}")

    fields: dict = {"term": None, "detail": None, "example": None, "key": None}
    for arg in _split_items(_balanced(item, item.index("("), "(", ")")):
        label, _, value = arg.partition(":")
        label, value = label.strip(), value.strip()
        if label not in fields:
            continue                       # page:/section: are structure, not prose
        if value == "nil":
            fields[label] = None
        else:
            fields[label], _ = _read_string(value, 0)
    if not fields["term"] or not fields["detail"]:
        raise ParseError(f"topic missing term or detail: {item[:60]!r}")
    return fields


def read_pages(src: str) -> dict[str, list[tuple[str, list[dict]]]]:
    """{page: [(section title, [topic, ...]), ...]} in the order the app shows them."""
    pages: dict[str, list[tuple[str, list[dict]]]] = {}
    for page in ("help", "faq"):
        m = re.search(rf"static let {page}: \[ManualSection\] = \[", src)
        if not m:
            raise ParseError(f"no section list for page {page!r}")
        sections = []
        for entry in _split_items(_balanced(src, m.end() - 1, "[", "]")):
            title = re.search(r'title:\s*"((?:[^"\\]|\\.)*)"', entry)
            topics = re.search(r"topics:\s*([A-Za-z][A-Za-z0-9]*)", entry)
            if not title or not topics:
                raise ParseError(f"unparsable section: {entry[:60]!r}")
            items = _split_items(_array_body(src, topics.group(1)))
            sections.append((title.group(1), [_parse_topic(i) for i in items]))
        pages[page] = sections
    return pages


# -------------------------------------------------------------------- rendering

def render(page: str, title: str, blurb: str,
           sections: list[tuple[str, list[dict]]]) -> str:
    out = [BANNER, "", f"# {title}", "", blurb, ""]
    for section_title, topics in sections:
        out += [f"## {section_title}", ""]

        # A section whose topics are all keystrokes is a lookup table, and reads
        # like one. Everything else is question-and-answer prose.
        if topics and all(t["key"] for t in topics):
            out += ["| Key | What it does |", "| --- | --- |"]
            for t in topics:
                cap = t["term"].replace("|", "\\|")
                detail = t["detail"].replace("\n", " ").replace("|", "\\|")
                out += [f"| `{cap}` | {detail} |"]
            out += [""]
            continue

        for t in topics:
            out += [f"### {t['term']}", "", t["detail"], ""]
            if t["example"]:
                out += ["```", t["example"], "```", ""]
    return "\n".join(out).rstrip() + "\n"


HELP_BLURB = (
    "Seedbed's reference: the keys, the vocabulary, and what to do when "
    "something looks wrong.\n\nThis is the same text the app shows under Help, "
    "generated from it so the two cannot disagree. If you have the app, press "
    "`?` in the panel instead."
)
FAQ_BLURB = (
    "The questions people actually arrive with.\n\nHelp is the reference; this "
    "is the other half. It is the same text the app shows under FAQ, generated "
    "from it so the two cannot disagree."
)

TARGETS = {
    "help": (ROOT / "HELP.md", "Seedbed Help", HELP_BLURB),
    "faq": (ROOT / "FAQ.md", "Seedbed FAQ", FAQ_BLURB),
}


def build() -> dict[Path, str]:
    pages = read_pages(MANUAL.read_text(encoding="utf-8"))
    return {
        TARGETS[page][0]: render(page, TARGETS[page][1], TARGETS[page][2], sections)
        for page, sections in pages.items()
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report staleness instead of rewriting")
    args = ap.parse_args()

    stale = []
    for path, text in build().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(path)
        if not args.check:
            path.write_text(text, encoding="utf-8")

    rel = [str(p.relative_to(ROOT)) for p in stale]
    if args.check:
        if stale:
            print("stale, regenerate with Scripts/generate-help-docs.py:", *rel,
                  file=sys.stderr)
            return 1
        print("HELP.md and FAQ.md are current")
        return 0
    print("rewrote " + ", ".join(rel) if stale else "already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
